### ISSUE TITLE
Would a mysql store module be needed?

### ISSUE THREAD

**Issue by jack60612** [Chia-Network/pool-reference#148]
@william-gr I built a mysql store module while i was making my pool and i was wondering if you guys would want it?

**Comment by jack60612** [comment]
i also built some pplns code

**Comment by william-gr** [comment]
@william-gr I dont work for Chia, just a regular contributor. However they probably wouldnt mind if you create a PR with these.

**Comment by jack60612** [comment]
yep sorry for @ing you then ya i was making a pool so i definitely made a bunch of changes lol 
but ya i'll probs send it in tomorrow it just uses aiomysql  instead of aiosqlite and a bunch of changes for the different command structure

**Comment by jack60612** [comment]
ya should i just add an option to the config file or just submit the stor file

**Comment by chrishp** [comment]
Did you ever upload this?

**Comment by jack60612** [comment]
nope

> Did you ever upload this?

**Comment by jack60612** [comment]
@chrishp

**Comment by ppolewicz** [comment]
@chrishp I've been scaling a Chia pool for high traffic, but the way we did it was not through adding a store file with a mysql driver and we have very good reasons why. I hope I can write a blog post about it one day but you may think about how this will scale under load in the age of Pool Wars..

**Comment by jack60612** [comment]
ya i am using a store file but its heavily optimized so it should work fine

**Comment by ppolewicz** [comment]
ah, but won't those optimizations also apply to sqlite?

**Comment by jack60612** [comment]
> ah, but won't those optimizations also apply to sqlite?
Alot of them are mariadb based and im not sure if they would work in sqlite.
i need to make it so that you can edit it from the config but my main issue with contributing is that it has all of these changes for my pool so ill need to take them all out before contributing and i don't know if the other  contributors will like the way i implemented these extra features. so i primarily just haven't bothered 
@ppolewicz

**Comment by ppolewicz** [comment]
Right, but if we all did things like this, the whole opensource thing wouldn't go very far.

You mentioned that you added a store file. Just so you know, one of my clients needed a custom store, so what we did is we have added the store abstraction layer and opensourced it (and you used it, which was relatively easy because the store was separated from the other stuff already :) ), only then to implement a pool-specific store (which sadly cannot be opensourced). If there are common optimizations, maybe share some of them with the community? Small PRs are usually better. Also, if you share it and get some of them merged, then updating your code so that it follows the newest features in the pool-reference will be easier, you won't have to merge your changes with the upstream that much.

**Comment by jack60612** [comment]
true

**Comment by jack60612** [comment]
#191

**Comment by jack60612** [comment]
Closed as discussion has been moved to the pr
