### ISSUE TITLE
Pool Reference Required ports?

### ISSUE THREAD

**Issue by alierdemsunar** [Chia-Network/pool-reference#216]
Hello team,
Which ports required for pool reference? We are working on Firewall for security. We opened only TCP 443 is it right?

**Comment by mariano54** [comment]
You can choose your port.

**Comment by wearechiarex** [comment]
> You can choose your port.

Okey so, how can I check is it working properly? Because I'm worried, Sometimes we can't find any blocks for 3 days. And we have over 10PiB space. We think it might be something unhealthy. Can we ask you to check it as a pool operator? Because everything looks fine, including the log (no WARNING and ERROR).

https://tr.node.chiarex.net
